name: Recent Offical Accounts

on:
  schedule:
    - cron: "0 0 * * *"
    # https://docs.github.com/zh/actions/using-workflows/events-that-trigger-workflows#schedule
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-readme-feed
    steps:
      - uses: actions/checkout@v4
      - uses: sarisia/actions-readme-feed@v1
        with:
          url: "http://218.203.155.136:52005/feeds/MP_WXS_3865908576.json"
          file: "README.md"
      - uses: sarisia/actions-commit@master
